### ISSUE TITLE
How to  stop scrolling of the chat to the top and putting the chat message in the current postion after typing load more in the top 

### ISSUE THREAD

**Issue by ghost** [theomessin/vue-chat-scroll#80] opened 2020-05-21 09:34 UTC
problem description
I have created a chat where it load only 20 message . and if i scroll to top we will see the load more button which will load more 20 message but it directly reach to the top . how can we stop scrolling the chat to top and make it stay in the current position

**Comment by theomessin** [comment] 2020-05-21 10:29
Sounds like a duplicate of https://github.com/theomessin/vue-chat-scroll/issues/68 to me. @gamenic-praful can you confirm?

**Comment by ghost** [comment] 2020-05-22 04:51
> Sounds like a duplicate of #68 to me. @gamenic-praful can you confirm?

yes its dublicate of #68 but this jsfiddle in this issue is no more available . is there any other option @theomessin 

https://jsfiddle.net/theomessin/zhjdm0qb/

**Comment by ghost** [comment] 2020-05-22 05:01
@theomessin sir , i have tried @v-chat-scroll-top-reached="topReached" but it was not invoking the method . what might be the problem ?

**Comment by theomessin** [comment] 2020-05-22 06:16
@gamenic-praful you're can use the 2.0-alpha or wait until version 2.0 has been released.

**Closed as completed** 2020-05-22 06:16 UTC
Labels: awaiting reply
