### ISSUE TITLE
Failed to resolve directive: chat-scroll

### ISSUE THREAD

**Issue by wuxingjiang** [theomessin/vue-chat-scroll#14] opened 2017-07-07 04:50 UTC
![image](https://user-images.githubusercontent.com/15045361/27943555-d35e3620-6312-11e7-826b-180347dec97d.png)

**Comment by AhmedBoustani** [comment] 2017-07-07 14:34
+1

**Comment by theomessin** [comment] 2017-07-07 18:06
Duplicate of #8

**Closed by theomessin** 2017-07-07 18:06 UTC
Labels: duplicate

**Comment by theomessin** [comment] 2017-07-09 05:42
See the solution of #8
