### ISSUE TITLE
use on scrolling console like output

### ISSUE THREAD

**Issue by Vad1mo** [theomessin/vue-chat-scroll#37] opened 2018-12-29 15:55 UTC
I am displaying console output to trace logs and would like to use to plugin to scroll to the bottom

However, it doesn't scroll to the bottom. The class `output-cmd`has a max-hight set to 300px so there are scrollbars.
 
```html
    <div>
      <div class='console'>
        <div class='console-inner'>
          <div class='output-cmd' id="cont" v-chat-scroll>
            <pre>
                <code>
                    {{ logarray.join("\n") }}
                </code>
            </pre>
          </div>
        </div>
      </div>
    </div>
```

**Comment by theomessin** [comment] 2019-01-01 17:52
Hmm. That's weird. Only thing I can think of is that you might have the attribute applied to the wrong element... Let me see if I can replicate the issue locally.

**Comment by Zendrex** [comment] 2019-01-04 01:53
I'm also desiring to use this the same way, however its not working. My code is below. I am guessing I am simply doing this wrong somehow.
```
<template>
    <v-card height="100%" class="consoleLog elevation-5">
        <transition-group name="slide" enter-active-class="fadeInUp" leave-active-class="fadeOutDown" mode="out-in" tag="ul" class="logList" v-chat-scroll>
            <li v-for="log in logs" v-bind:key="log.id" class="logItem" v-html="log.message"/>
        </transition-group>
    </v-card>
</template>

...

<style lang="scss" scoped>
.consoleLog {
    background: rgb(0, 0, 0);
    background: linear-gradient(
        130deg,
        rgba(0, 0, 0, 1) 0%,
        rgba(47, 47, 47, 1) 100%
    );

    .logList {
        position: absolute;
        width: 100%;
        overflow-y: scroll;
        height: 100%;
        padding: 0px;
        list-style: none;
    }

    .logItem {
        padding-left: 5px;
        padding-right: 5px;
        padding-top: 3px;
        padding-bottom: 3px;
        margin-left: 10px;
        animation-duration: 0.35s;
        &:first-child {
            margin-top: 5px;
        }
        &:last-child {
            margin-bottom: 5px;
        }
    }
}
</style>
```

**Comment by theomessin** [comment] 2019-01-04 08:17
@Zendrex your issue seems like a duplicate of #17. As far as I am aware, you can't use this directive with transition-groups.

**Comment by theomessin** [comment] 2019-01-04 08:19
@Vad1mo can you maybe give me your CSS as well? If you can make a JSFiddle reproducing this, that'd be great!

**Comment by vesper8** [comment] 2019-01-08 13:57
I'm also using it for this same purpose and it's working fine for me. Have you tried actually using a UL/LI combo ? 

```
              <ul
                v-chat-scroll
                class="console"
              >
                <li
                  v-for="(message, key) in logItems"
                  :key="key"
                  :class="message.type"
                  v-html="message.message"
                />
              </ul>
```

Also make sure that when you are adding new items to the thing that is mapped to your v-for, that you use the .push() command

**Comment by theomessin** [comment] 2019-01-13 23:47
Closing this issue due to inactivity. Feel free to re-open it if this is still... an issue :wink:

**Closed by theomessin** 2019-01-13 23:47 UTC
Labels: bug
